### PR TITLE
Fix launcher Java detection

### LINKED ISSUE #15: fails to open even after the game has been launched with official launcher
There have been several reports of this now. The installer requires that MC 1.18.2 or above must have been launched with the Official launcher at least once. But doing that does not stop the pop up from appearing for some users.

### PR DESCRIPTION
**Pull request by LostLuma**
Resolves #15.

To do so I've merged upstream as there was a change [searching more possible installer paths](https://github.com/QuiltMC/quilt-installer/commit/9d5828e5011871c7a9e0cea1b51776cab05f4a96) and [fixed the detection of the delta runtime](https://github.com/QuiltMC/quilt-installer/pull/48) (used by 1.20.5 and above).

### CODE REVIEW

File: src/java8/java/org/quiltmc/installer/Main.java [hunk 1]
```diff
@@ -0,0 +1,96 @@
...
+                try {
+                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
+                } catch (ClassNotFoundException | UnsupportedLookAndFeelException | IllegalAccessException |
+                         InstantiationException e) {
+                    // oh well
+                    e.printStackTrace();
+                }
+
+
+                showPopup("Quilt Installer crashed!", "<html>Quilt Installer needs Java 17 to run.<br><br>" +
```
Comment (SpaceWalkerRS) [inline src/java8/java/org/quiltmc/installer/Main.java:53]: this should say 'Ornithe' rather than 'Quilt'

**Review by SpaceWalkerRS — CHANGES_REQUESTED** [review]

**Comment by SpaceWalkerRS** [comment]
The tests are successful, Just one tiny change needed so once that's done this can be merged.

File: src/java8/java/org/quiltmc/installer/Main.java (hunk 1 above)
Comment (LostLuma) [reply src/java8/java/org/quiltmc/installer/Main.java]: Updated!

**Review by SpaceWalkerRS — APPROVED** [review]
